name: Deploy Test 

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      IMAGE_NAME: api_rest_image
      APP_SERVICE_NAME: apitheliko
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Loggin Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login Azure Container Registry
      run: az acr login --name $ACR_NAME

    - name: Build Docker Image
      run: docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} -f Dockerfile.prod .
      env:
        DOCKER_BUILDKIT: 1

    - name: Push Docker Image
      run: docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
      env:
        DOCKER_BUILDKIT: 1

    - name: Deploy Docker Image
      run: az webapp config container set --name $APP_SERVICE_NAME --resource-group $RESOURCE_GROUP_NAME --docker-custom-image-name $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
      env:
        DOCKER_BUILDKIT: 1

    - name: Restart Web App
      run: az webapp restart --name $APP_SERVICE_NAME --resource-group $RESOURCE_GROUP_NAME
